Repository hamsik22/NBC-W6-Kiosk, pull requests merged in 2024-11, with the labels that each got.

#3 feat: 카테고리 화면 작업 (#2)
  NBC-W6-Kiosk/Controller/KioskViewController.swift
Labels: feat, refactor

#4 Revert "#2-화면작업"
  NBC-W6-Kiosk/Controller/KioskViewController.swift
Labels: feat

#7 #2- 카테고리 및 메뉴 화면 작업
  NBC-W6-Kiosk/Assets.xcassets/gray0.colorset/Contents.json
  NBC-W6-Kiosk/Assets.xcassets/gray2.colorset/Contents.json
  NBC-W6-Kiosk/Controller/KioskViewController.swift
  NBC-W6-Kiosk/Enums/MenuCategory.swift
  NBC-W6-Kiosk/Model/MenuItem.swift
  NBC-W6-Kiosk/View/MenuItemCell.swift
Labels: feat

#9 #6 model
  NBC-W6-Kiosk/Controller/KioskViewController.swift
  NBC-W6-Kiosk/Enums/MenuCategory.swift
  NBC-W6-Kiosk/Model/Menu.swift
  NBC-W6-Kiosk/Model/MenuItem.swift
  NBC-W6-Kiosk/Model/Product.swift
  NBC-W6-Kiosk/Model/ShoppingBasket.swift
  NBC-W6-Kiosk/Utility/Observer/Observer.swift
  NBC-W6-Kiosk/Utility/Observer/Subject.swift
  NBC-W6-Kiosk/View/MenuItemCell.swift
Labels: feat

#14 [Add]: Add SnapKit Package
  NBC-W6-Kiosk.xcodeproj/project.pbxproj
  NBC-W6-Kiosk.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: hotfix

#18 #17 model
  NBC-W6-Kiosk.xcodeproj/project.pbxproj
  NBC-W6-Kiosk/Controller/KioskViewController.swift
  NBC-W6-Kiosk/Enums/MenuCategory.swift
  NBC-W6-Kiosk/Model/Menu.swift
  NBC-W6-Kiosk/Model/Product.swift
  NBC-W6-Kiosk/Model/ShoppingBasket.swift
  NBC-W6-Kiosk/Utility/Observer/Observer.swift
  NBC-W6-Kiosk/Utility/Observer/Subject.swift
  NBC-W6-Kiosk/View/MenuItemCell.swift
Labels: feat, fix

#20 #19 Color Assets 생성 및 설정, Alert Font 추가 기능 구현
  NBC-W6-Kiosk/Colors.xcassets/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/DisableBuyButtonFillColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/buyButtonFillColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/buyButtontextColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/cancelButtonStrokeColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/cartPriceColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/countColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/countRemitColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/englishNameColor.colorset/Contents.json
  NBC-W6-Kiosk/Colors.xcassets/textMainColor.colorset/Contents.json
  NBC-W6-Kiosk/Utility/Fonts.swift
Labels: feat, fix
